const byId=id=>document.getElementById(id);
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let current='tomorrow',running=false,stageLauncher=null;
const map=byId('commandMap'),mapLines=byId('mapLines');
const mapLayout=[['Олеся',28,67],['Дарина',38,84],['Зоряна',51,90],['Ярина',63,88],['Роксолана',76,80],['Марта',88,65],['Лада',76,63],['Калина',84,24],['Богдана',70,14],['Катерина',25,18],['Віра',27,57]];

byId('mapAgents').innerHTML=mapLayout.map(([name,left,top])=>{const a=agents.find(item=>item.name===name);return `<button class="agent-node" data-agent="${a.name}" style="--x:${left}%;--y:${top}%" type="button" aria-label="${a.name}: ${a.role}"><span>${a.name[0]}</span><small>${a.name}</small></button>`}).join('');
byId('teamGrid').innerHTML=agents.map((a,i)=>`<article class="agent-card ${i===0?'featured':''}" data-agent-card="${a.name}" tabindex="0"><span class="number">${String(i+1).padStart(2,'0')}</span><span class="avatar">${a.name[0]}</span><h3>${a.name}</h3><small>${a.role}</small><p>${a.desc}</p><div class="metric">↗ ${a.metric}</div><details><summary>${a.skills.length} скілів</summary><ul>${a.skills.map(s=>`<li>${s}</li>`).join('')}</ul></details></article>`).join('');
byId('tomorrowGrid').innerHTML=tomorrowTasks.map(([name,task],i)=>`<article class="tomorrow-card"><span class="task-time">${i===0?'09:00':'до 09:00'}</span><div class="avatar mini">${name[0]}</div><h3>${name}</h3><p>${task}</p></article>`).join('');

const observer=reduceMotion?null:new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12});
function reveal(root=document){if(reduceMotion||!observer)return;root.querySelectorAll('.agent-card,.tomorrow-card,.case-card,.stats,.section-heading,.rhythm').forEach(node=>{if(node.dataset.revealReady)return;node.dataset.revealReady='true';node.classList.add('reveal');observer.observe(node)})}
const nodeCopy={human:['GOVERNANCE 00','Віталій тримає контроль','Ти задаєш напрям, контекст і межі. Система повертає лише підготовлені рішення.'],goal:['ВХІД 01','Ціль визначає маршрут','Почни з очікуваного результату — карта підсвітить, кого залучає Соломія.'],context:['ВХІД 02','Контекст робить відповідь точною','Календар, нотатки, документи та попередні рішення стають робочою памʼяттю.'],constraints:['ВХІД 03','Обмеження зберігають контроль','Правила, бюджет, термін і дозволи лишаються видимими в маршруті.'],solomiia:['КЕРІВНИЦЯ ШТАБУ','Соломія збирає потрібну команду','Вона прибирає шум, розподіляє роботу й повертає один пакет рішень.'],approval:['FEEDBACK LOOP','Рішення лишається за Віталієм','Агентки готують результат. Зовнішня дія можлива лише після твого «ок».']};
function setDetail(kicker,title,text){byId('mapDetail').innerHTML=`<span class="detail-kicker">${kicker}</span><strong>${title}</strong><p>${text}</p>`}
function clearMap(){map.querySelectorAll('.route-active,.selected-node,.route-done').forEach(n=>n.classList.remove('route-active','selected-node','route-done'));mapLines.innerHTML='';byId('mapProgress').textContent='00 / 12'}
function selectAgent(name){const a=agents.find(item=>item.name===name);if(!a)return;clearMap();map.querySelector(`[data-agent="${name}"]`)?.classList.add('selected-node');setDetail(`АГЕНТКА · ${String(agents.indexOf(a)+1).padStart(2,'0')}`,a.name,`${a.role}. KPI: ${a.metric}. ${a.skills.length} скілів: ${a.skills.slice(0,3).join(' · ')}.`);document.querySelectorAll('[data-agent-card]').forEach(card=>card.classList.toggle('selected-card',card.dataset.agentCard===name))}
function selectNode(key){clearMap();map.querySelector(`[data-node="${key}"]`)?.classList.add('selected-node');const c=nodeCopy[key];if(c)setDetail(...c)}
function nodeCenter(node){const r=node.getBoundingClientRect(),base=map.getBoundingClientRect();return {x:r.left-base.left+r.width/2,y:r.top-base.top+r.height/2}}
function lineBetween(a,b,active=false){if(!a||!b)return;const p=nodeCenter(a),q=nodeCenter(b),line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',p.x);line.setAttribute('y1',p.y);line.setAttribute('x2',q.x);line.setAttribute('y2',q.y);line.classList.toggle('active-line',active);mapLines.append(line)}
function drawRoute(names=[],activeIndex=-1){mapLines.innerHTML='';const sol=map.querySelector('[data-node="solomiia"]'),human=map.querySelector('[data-node="human"]'),approval=map.querySelector('[data-node="approval"]'),goal=map.querySelector('[data-node="goal"]');lineBetween(goal,sol,activeIndex>=0);lineBetween(human,sol,activeIndex>=0);names.forEach((name,index)=>{const node=name==='Соломія'?sol:map.querySelector(`[data-agent="${name}"]`);lineBetween(sol,node,index<=activeIndex);if(node&&index<=activeIndex)node.classList.add(index===activeIndex?'route-active':'route-done')});if(activeIndex>=names.length){lineBetween(sol,approval,true);approval.classList.add('route-active')}}
window.addEventListener('resize',()=>{if(running)drawRoute(scenarios[current].flow.map(step=>step[0]),-1)});

function renderScenario(){const s=scenarios[current];document.body.classList.remove('agent-running');clearMap();byId('sourceCard').innerHTML=s.source;byId('flow').innerHTML=s.flow.map(([name,job],i)=>`<div class="flow-step" data-step="${i}"><span class="avatar mini">${name[0]}</span><div><strong>${name}</strong><span>${job}</span></div><b class="state">○</b></div>`).join('');byId('flowStatus').textContent='очікує запуску';byId('result').classList.add('hidden');byId('resultEmpty').classList.remove('hidden');byId('runDemo').disabled=false;running=false;selectNode('human')}
document.querySelectorAll('.scenario-tab').forEach(btn=>btn.addEventListener('click',()=>{if(running)return;document.querySelector('.scenario-tab.active').classList.remove('active');btn.classList.add('active');current=btn.dataset.scenario;renderScenario()}));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){if(running)return;running=true;document.body.classList.add('agent-running');byId('runDemo').disabled=true;byId('flowStatus').textContent='маршрут активний…';const s=scenarios[current],names=s.flow.map(step=>step[0]),steps=[...document.querySelectorAll('.flow-step')];clearMap();const sol=map.querySelector('[data-node="solomiia"]'),goal=map.querySelector('[data-node="goal"]');goal.classList.add('route-active');sol.classList.add('route-active');drawRoute(names,-1);setDetail('LIVE ROUTE','Соломія формує маршрут',`Сценарій «${document.querySelector('.scenario-tab.active').textContent}» активний.`);await wait(reduceMotion?80:700);for(const [index,step] of steps.entries()){const name=names[index],a=agents.find(item=>item.name===name);step.classList.add('active');step.querySelector('.state').textContent='•••';drawRoute(names,index);setDetail(`АКТИВНА АГЕНТКА · ${index+1}/${names.length}`,a.name,`${a.role}. Зараз: ${s.flow[index][1]}.`);await wait(reduceMotion?100:1050);step.classList.remove('active');step.classList.add('done');step.querySelector('.state').textContent='✓'}drawRoute(names,names.length);byId('mapProgress').textContent=`${String(names.length).padStart(2,'0')} / ${String(names.length).padStart(2,'0')}`;byId('result').innerHTML=`<div class="result-summary"><strong>Соломія:</strong> ${s.summary}</div>${s.cards.map(c=>`<div class="board-card"><div class="board-head"><span class="system ${c[1]}">${c[0]}</span><span>•••</span></div><strong>${c[2]}</strong><div class="meta"><span>👤 ${c[3]}</span><span>◷ ${c[4]}</span><span>◆ ${c[5]}</span></div></div>`).join('')}<div class="approval">🔒 ${s.approval}</div>`;byId('resultEmpty').classList.add('hidden');byId('result').classList.remove('hidden');byId('flowStatus').textContent='готово · очікує затвердження';setDetail('HUMAN APPROVAL','Пакет рішень готовий',s.approval);running=false;window.setTimeout(()=>document.body.classList.remove('agent-running'),reduceMotion?0:900)}
byId('runDemo').addEventListener('click',run);byId('resetDemo').addEventListener('click',renderScenario);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')run()});
map.addEventListener('click',event=>{const agent=event.target.closest('[data-agent]'),node=event.target.closest('[data-node]');if(agent)selectAgent(agent.dataset.agent);if(node)selectNode(node.dataset.node)});document.querySelectorAll('[data-agent-card]').forEach(card=>card.addEventListener('click',()=>selectAgent(card.dataset.agentCard)));
function toggleStage(open){if(open){stageLauncher=document.activeElement;document.body.classList.add('stage-mode');byId('stageClose').focus()}else{document.body.classList.remove('stage-mode');stageLauncher?.focus()}if(running)drawRoute(scenarios[current].flow.map(step=>step[0]),-1)}
byId('stageToggle').addEventListener('click',()=>toggleStage(true));byId('stageClose').addEventListener('click',()=>toggleStage(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('stage-mode'))toggleStage(false)});
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!document.body.classList.contains('stage-mode'))return;const focusable=[...map.querySelectorAll('button:not([disabled])')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
let drag=null;map.addEventListener('pointerdown',event=>{const node=event.target.closest('[data-agent]');if(!node||window.matchMedia('(max-width:900px)').matches)return;drag={node,startX:event.clientX,startY:event.clientY,dx:0,dy:0};node.setPointerCapture(event.pointerId);node.classList.add('dragging')});map.addEventListener('pointermove',event=>{if(!drag)return;drag.dx+=event.clientX-drag.startX;drag.dy+=event.clientY-drag.startY;drag.startX=event.clientX;drag.startY=event.clientY;drag.node.style.setProperty('--drag-x',`${drag.dx}px`);drag.node.style.setProperty('--drag-y',`${drag.dy}px`)});map.addEventListener('pointerup',()=>{if(!drag)return;drag.node.classList.remove('dragging');drag=null});
const categories=['Усі',...new Set(useCases.map(c=>c[1]))];let category='Усі';byId('filters').innerHTML=categories.map((c,i)=>`<button class="filter ${i===0?'active':''}" data-cat="${c}">${c}</button>`).join('');function renderCases(){const q=byId('caseSearch').value.trim().toLowerCase(),rows=useCases.filter(c=>(category==='Усі'||c[1]===category)&&(`${c[0]} ${c[2]} ${skillOwner[c[0]]}`).toLowerCase().includes(q));byId('caseCount').textContent=`Показано ${rows.length} із ${useCases.length}`;byId('caseGrid').innerHTML=rows.map(c=>`<article class="case-card ${c[3]?'recommended':''}"><div class="case-top"><span class="case-category">${c[1]}</span><span class="owner">${skillOwner[c[0]]}</span></div><h3>${c[0]}</h3><p>${c[2]}</p></article>`).join('');reveal(byId('caseGrid'))}byId('caseSearch').addEventListener('input',renderCases);byId('filters').addEventListener('click',e=>{const btn=e.target.closest('.filter');if(!btn)return;document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');category=btn.dataset.cat;byId('caseGrid').classList.add('is-filtering');renderCases();requestAnimationFrame(()=>byId('caseGrid').classList.remove('is-filtering'))});
renderScenario();renderCases();reveal();
